/*
PingOne Platform API - Credentials

Testing PingOneCredentialsCredentialVerificationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PingOneCredentialsCredentialVerificationsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PingOneCredentialsCredentialVerificationsApiService CreateCredentialVerificationPresentationSessionNative", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environmentID string

		httpRes, err := apiClient.PingOneCredentialsCredentialVerificationsApi.CreateCredentialVerificationPresentationSessionNative(context.Background(), environmentID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PingOneCredentialsCredentialVerificationsApiService ReadCredentialVerificationCredentialData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environmentID string
		var credentialsVerificationID string

		httpRes, err := apiClient.PingOneCredentialsCredentialVerificationsApi.ReadCredentialVerificationCredentialData(context.Background(), environmentID, credentialsVerificationID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PingOneCredentialsCredentialVerificationsApiService ReadOneCredentialVerificationStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environmentID string
		var credentialsVerificationID string

		httpRes, err := apiClient.PingOneCredentialsCredentialVerificationsApi.ReadOneCredentialVerificationStatus(context.Background(), environmentID, credentialsVerificationID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
