/*
PingOne Platform API - Credentials

The PingOne Platform API covering the PingONe Credentials service

API version: 2023-03-30
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// PingOneCredentialsCredentialIssuanceRulesApiService PingOneCredentialsCredentialIssuanceRulesApi service
type PingOneCredentialsCredentialIssuanceRulesApiService service

type ApiApplyCredentialIssuanceRuleStagedChangesRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
	contentType *string
	body *map[string]interface{}
}

func (r ApiApplyCredentialIssuanceRuleStagedChangesRequest) Authorization(authorization string) ApiApplyCredentialIssuanceRuleStagedChangesRequest {
	r.authorization = &authorization
	return r
}

func (r ApiApplyCredentialIssuanceRuleStagedChangesRequest) ContentType(contentType string) ApiApplyCredentialIssuanceRuleStagedChangesRequest {
	r.contentType = &contentType
	return r
}

func (r ApiApplyCredentialIssuanceRuleStagedChangesRequest) Body(body map[string]interface{}) ApiApplyCredentialIssuanceRuleStagedChangesRequest {
	r.body = &body
	return r
}

func (r ApiApplyCredentialIssuanceRuleStagedChangesRequest) Execute() (*http.Response, error) {
	return r.ApiService.ApplyCredentialIssuanceRuleStagedChangesExecute(r)
}

/*
ApplyCredentialIssuanceRuleStagedChanges Apply Credential Issuance Rule Staged Changes

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiApplyCredentialIssuanceRuleStagedChangesRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ApplyCredentialIssuanceRuleStagedChanges(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiApplyCredentialIssuanceRuleStagedChangesRequest {
	return ApiApplyCredentialIssuanceRuleStagedChangesRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ApplyCredentialIssuanceRuleStagedChangesExecute(r ApiApplyCredentialIssuanceRuleStagedChangesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ApplyCredentialIssuanceRuleStagedChanges")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/stagedChanges"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	if r.contentType != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Content-Type", r.contentType, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateCredentialIssuanceRuleRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	authorization *string
	body *map[string]interface{}
}

func (r ApiCreateCredentialIssuanceRuleRequest) Authorization(authorization string) ApiCreateCredentialIssuanceRuleRequest {
	r.authorization = &authorization
	return r
}

func (r ApiCreateCredentialIssuanceRuleRequest) Body(body map[string]interface{}) ApiCreateCredentialIssuanceRuleRequest {
	r.body = &body
	return r
}

func (r ApiCreateCredentialIssuanceRuleRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateCredentialIssuanceRuleExecute(r)
}

/*
CreateCredentialIssuanceRule Create Credential Issuance Rule

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @return ApiCreateCredentialIssuanceRuleRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) CreateCredentialIssuanceRule(ctx context.Context, envID string, credentialTypeID string) ApiCreateCredentialIssuanceRuleRequest {
	return ApiCreateCredentialIssuanceRuleRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) CreateCredentialIssuanceRuleExecute(r ApiCreateCredentialIssuanceRuleRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.CreateCredentialIssuanceRule")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteCredentialIssuanceRuleRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
}

func (r ApiDeleteCredentialIssuanceRuleRequest) Authorization(authorization string) ApiDeleteCredentialIssuanceRuleRequest {
	r.authorization = &authorization
	return r
}

func (r ApiDeleteCredentialIssuanceRuleRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteCredentialIssuanceRuleExecute(r)
}

/*
DeleteCredentialIssuanceRule Delete Credential Issuance Rule

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiDeleteCredentialIssuanceRuleRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) DeleteCredentialIssuanceRule(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiDeleteCredentialIssuanceRuleRequest {
	return ApiDeleteCredentialIssuanceRuleRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) DeleteCredentialIssuanceRuleExecute(r ApiDeleteCredentialIssuanceRuleRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.DeleteCredentialIssuanceRule")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReadAllCredentialIssuanceRulesRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	authorization *string
}

func (r ApiReadAllCredentialIssuanceRulesRequest) Authorization(authorization string) ApiReadAllCredentialIssuanceRulesRequest {
	r.authorization = &authorization
	return r
}

func (r ApiReadAllCredentialIssuanceRulesRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReadAllCredentialIssuanceRulesExecute(r)
}

/*
ReadAllCredentialIssuanceRules Read All Credential Issuance Rules

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @return ApiReadAllCredentialIssuanceRulesRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadAllCredentialIssuanceRules(ctx context.Context, envID string, credentialTypeID string) ApiReadAllCredentialIssuanceRulesRequest {
	return ApiReadAllCredentialIssuanceRulesRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadAllCredentialIssuanceRulesExecute(r ApiReadAllCredentialIssuanceRulesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ReadAllCredentialIssuanceRules")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReadCredentialIssuanceRuleStagedChangesRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
}

func (r ApiReadCredentialIssuanceRuleStagedChangesRequest) Authorization(authorization string) ApiReadCredentialIssuanceRuleStagedChangesRequest {
	r.authorization = &authorization
	return r
}

func (r ApiReadCredentialIssuanceRuleStagedChangesRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReadCredentialIssuanceRuleStagedChangesExecute(r)
}

/*
ReadCredentialIssuanceRuleStagedChanges Read Credential Issuance Rule Staged Changes

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiReadCredentialIssuanceRuleStagedChangesRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleStagedChanges(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiReadCredentialIssuanceRuleStagedChangesRequest {
	return ApiReadCredentialIssuanceRuleStagedChangesRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleStagedChangesExecute(r ApiReadCredentialIssuanceRuleStagedChangesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ReadCredentialIssuanceRuleStagedChanges")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/stagedChanges"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReadCredentialIssuanceRuleUsageCountsRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
}

func (r ApiReadCredentialIssuanceRuleUsageCountsRequest) Authorization(authorization string) ApiReadCredentialIssuanceRuleUsageCountsRequest {
	r.authorization = &authorization
	return r
}

func (r ApiReadCredentialIssuanceRuleUsageCountsRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReadCredentialIssuanceRuleUsageCountsExecute(r)
}

/*
ReadCredentialIssuanceRuleUsageCounts Read Credential Issuance Rule Usage Counts

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiReadCredentialIssuanceRuleUsageCountsRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleUsageCounts(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiReadCredentialIssuanceRuleUsageCountsRequest {
	return ApiReadCredentialIssuanceRuleUsageCountsRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleUsageCountsExecute(r ApiReadCredentialIssuanceRuleUsageCountsRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ReadCredentialIssuanceRuleUsageCounts")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageCounts"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReadCredentialIssuanceRuleUsageDetailsRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
}

func (r ApiReadCredentialIssuanceRuleUsageDetailsRequest) Authorization(authorization string) ApiReadCredentialIssuanceRuleUsageDetailsRequest {
	r.authorization = &authorization
	return r
}

func (r ApiReadCredentialIssuanceRuleUsageDetailsRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReadCredentialIssuanceRuleUsageDetailsExecute(r)
}

/*
ReadCredentialIssuanceRuleUsageDetails Read Credential Issuance Rule Usage Details

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiReadCredentialIssuanceRuleUsageDetailsRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleUsageDetails(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiReadCredentialIssuanceRuleUsageDetailsRequest {
	return ApiReadCredentialIssuanceRuleUsageDetailsRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadCredentialIssuanceRuleUsageDetailsExecute(r ApiReadCredentialIssuanceRuleUsageDetailsRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ReadCredentialIssuanceRuleUsageDetails")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}/usageDetails"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiReadOneCredentialIssuanceRuleRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
}

func (r ApiReadOneCredentialIssuanceRuleRequest) Authorization(authorization string) ApiReadOneCredentialIssuanceRuleRequest {
	r.authorization = &authorization
	return r
}

func (r ApiReadOneCredentialIssuanceRuleRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReadOneCredentialIssuanceRuleExecute(r)
}

/*
ReadOneCredentialIssuanceRule Read One Credential Issuance Rule

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiReadOneCredentialIssuanceRuleRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadOneCredentialIssuanceRule(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiReadOneCredentialIssuanceRuleRequest {
	return ApiReadOneCredentialIssuanceRuleRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) ReadOneCredentialIssuanceRuleExecute(r ApiReadOneCredentialIssuanceRuleRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.ReadOneCredentialIssuanceRule")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateCredentialIssuanceRuleRequest struct {
	ctx context.Context
	ApiService *PingOneCredentialsCredentialIssuanceRulesApiService
	envID string
	credentialTypeID string
	credentialIssuanceRuleID string
	authorization *string
	body *map[string]interface{}
}

func (r ApiUpdateCredentialIssuanceRuleRequest) Authorization(authorization string) ApiUpdateCredentialIssuanceRuleRequest {
	r.authorization = &authorization
	return r
}

func (r ApiUpdateCredentialIssuanceRuleRequest) Body(body map[string]interface{}) ApiUpdateCredentialIssuanceRuleRequest {
	r.body = &body
	return r
}

func (r ApiUpdateCredentialIssuanceRuleRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateCredentialIssuanceRuleExecute(r)
}

/*
UpdateCredentialIssuanceRule Update Credential Issuance Rule

This PingOne collection contains only the REST API request examples without documentation. For complete documentation, go to <a href="https://apidocs.pingidentity.com/pingone/platform/v1/api/">apidocs.pingidentity.com</a>.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param envID
 @param credentialTypeID
 @param credentialIssuanceRuleID
 @return ApiUpdateCredentialIssuanceRuleRequest
*/
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) UpdateCredentialIssuanceRule(ctx context.Context, envID string, credentialTypeID string, credentialIssuanceRuleID string) ApiUpdateCredentialIssuanceRuleRequest {
	return ApiUpdateCredentialIssuanceRuleRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		credentialTypeID: credentialTypeID,
		credentialIssuanceRuleID: credentialIssuanceRuleID,
	}
}

// Execute executes the request
func (a *PingOneCredentialsCredentialIssuanceRulesApiService) UpdateCredentialIssuanceRuleExecute(r ApiUpdateCredentialIssuanceRuleRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PingOneCredentialsCredentialIssuanceRulesApiService.UpdateCredentialIssuanceRule")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/environments/{envID}/credentialTypes/{credentialTypeID}/issuanceRules/{credentialIssuanceRuleID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", url.PathEscape(parameterValueToString(r.envID, "envID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialTypeID"+"}", url.PathEscape(parameterValueToString(r.credentialTypeID, "credentialTypeID")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialIssuanceRuleID"+"}", url.PathEscape(parameterValueToString(r.credentialIssuanceRuleID, "credentialIssuanceRuleID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
