/*
PingOne Platform API - Credentials

The PingOne Platform API covering the PingOne Credentials service

API version: 2023-03-30
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CredentialTypeEnvironment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialTypeEnvironment{}

// CredentialTypeEnvironment struct for CredentialTypeEnvironment
type CredentialTypeEnvironment struct {
	// A string that specifies the PingOne environment identifier (UUID) in which the credential type exists.
	Id string `json:"id"`
}

// NewCredentialTypeEnvironment instantiates a new CredentialTypeEnvironment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialTypeEnvironment(id string) *CredentialTypeEnvironment {
	this := CredentialTypeEnvironment{}
	this.Id = id
	return &this
}

// NewCredentialTypeEnvironmentWithDefaults instantiates a new CredentialTypeEnvironment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialTypeEnvironmentWithDefaults() *CredentialTypeEnvironment {
	this := CredentialTypeEnvironment{}
	return &this
}

// GetId returns the Id field value
func (o *CredentialTypeEnvironment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CredentialTypeEnvironment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CredentialTypeEnvironment) SetId(v string) {
	o.Id = v
}

func (o CredentialTypeEnvironment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialTypeEnvironment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableCredentialTypeEnvironment struct {
	value *CredentialTypeEnvironment
	isSet bool
}

func (v NullableCredentialTypeEnvironment) Get() *CredentialTypeEnvironment {
	return v.value
}

func (v *NullableCredentialTypeEnvironment) Set(val *CredentialTypeEnvironment) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialTypeEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialTypeEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialTypeEnvironment(val *CredentialTypeEnvironment) *NullableCredentialTypeEnvironment {
	return &NullableCredentialTypeEnvironment{value: val, isSet: true}
}

func (v NullableCredentialTypeEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialTypeEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


