/*
PingOne Platform API - Credentials

The PingOne Platform API covering the PingOne Credentials service

API version: 2023-03-30
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credentials

import (
	"encoding/json"
)

// checks if the CredentialDigitalWalletApplicationApplication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialDigitalWalletApplicationApplication{}

// CredentialDigitalWalletApplicationApplication struct for CredentialDigitalWalletApplicationApplication
type CredentialDigitalWalletApplicationApplication struct {
	// A string that specifies the identifier (UUID) of the PingOne application associated with the digital wallet app.
	Id string `json:"id"`
}

// NewCredentialDigitalWalletApplicationApplication instantiates a new CredentialDigitalWalletApplicationApplication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialDigitalWalletApplicationApplication(id string) *CredentialDigitalWalletApplicationApplication {
	this := CredentialDigitalWalletApplicationApplication{}
	this.Id = id
	return &this
}

// NewCredentialDigitalWalletApplicationApplicationWithDefaults instantiates a new CredentialDigitalWalletApplicationApplication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialDigitalWalletApplicationApplicationWithDefaults() *CredentialDigitalWalletApplicationApplication {
	this := CredentialDigitalWalletApplicationApplication{}
	return &this
}

// GetId returns the Id field value
func (o *CredentialDigitalWalletApplicationApplication) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CredentialDigitalWalletApplicationApplication) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CredentialDigitalWalletApplicationApplication) SetId(v string) {
	o.Id = v
}

func (o CredentialDigitalWalletApplicationApplication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialDigitalWalletApplicationApplication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableCredentialDigitalWalletApplicationApplication struct {
	value *CredentialDigitalWalletApplicationApplication
	isSet bool
}

func (v NullableCredentialDigitalWalletApplicationApplication) Get() *CredentialDigitalWalletApplicationApplication {
	return v.value
}

func (v *NullableCredentialDigitalWalletApplicationApplication) Set(val *CredentialDigitalWalletApplicationApplication) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialDigitalWalletApplicationApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialDigitalWalletApplicationApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialDigitalWalletApplicationApplication(val *CredentialDigitalWalletApplicationApplication) *NullableCredentialDigitalWalletApplicationApplication {
	return &NullableCredentialDigitalWalletApplicationApplication{value: val, isSet: true}
}

func (v NullableCredentialDigitalWalletApplicationApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialDigitalWalletApplicationApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


